### ISSUE TITLE
using anaconda to run demo.py

### ISSUE THREAD

**Issue by migero** [errno-mmd/VMD-Lifting#4]
WARNING:tensorflow:From D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
D:\OpenMMD\VMD-Lifting-0.2/packages\lifting\utils\upright_fast.py:206: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  p_copy.T, res[j].T)
Traceback (most recent call last):
  File "demo.py", line 65, in <module>
    sys.exit(main())
  File "demo.py", line 46, in main
    display_results(image, pose_2d, visibility, pose_3d)
  File "demo.py", line 52, in display_results
    draw_limbs(in_image, data_2d, joint_visibility)
  File "D:\OpenMMD\VMD-Lifting-0.2/packages\lifting\utils\draw.py", line 43, in draw_limbs
    _COLORS[lid], LIMB_DRAW_SIZE*_NORMALISATION_FACTOR , 16)
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\drawing.cpp:1811: error: (-215:Assertion failed) 0 < thickness && thickness <= MAX_THICKNESS in function 'cv::line'

**Comment by migero** [comment]
pip list 


Package              Version
-------------------- -------------------
absl-py              0.8.1
astor                0.8.0
cachetools           3.1.1
certifi              2019.11.28
chardet              3.0.4
cmake                3.15.3
cycler               0.10.0
decorator            4.4.1
dlib                 19.7.0
gast                 0.2.2
google-auth          1.8.2
google-auth-oauthlib 0.4.1
google-pasta         0.1.8
grpcio               1.25.0
h5py                 2.9.0
idna                 2.8
imageio              2.6.1
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
kiwisolver           1.1.0
Markdown             3.1.1
matplotlib           3.1.2
mkl-fft              1.0.15
mkl-random           1.1.0
mkl-service          2.3.0
mock                 3.0.5
networkx             2.4
numpy                1.17.4
oauthlib             3.1.0
opencv-python        4.1.2.30
opt-einsum           3.1.0
Pillow               6.2.1
pip                  19.3.1
protobuf             3.11.1
pyasn1               0.4.8
pyasn1-modules       0.2.7
pyparsing            2.4.5
PyQt5                5.13.2
PyQt5-sip            12.7.0
pyreadline           2.1
python-dateutil      2.8.1
PyWavelets           1.1.1
requests             2.22.0
requests-oauthlib    1.3.0
rsa                  4.0
scikit-image         0.16.2
scipy                1.3.3
setuptools           42.0.2.post20191203
six                  1.13.0
tensorboard          1.14.0
tensorflow           1.14.0
tensorflow-estimator 1.14.0
tensorflow-gpu       2.0.0
termcolor            1.1.0
urllib3              1.25.7
Werkzeug             0.16.0
wheel                0.33.6
wincertstore         0.2
wrapt                1.11.2

**Comment by errno-mmd** [comment]
The demo.py works well with opencv-python 4.1.2.30 in my environment.

> cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\drawing.cpp:1811: error: (-215:Assertion failed) 0 < thickness && thickness <= MAX_THICKNESS in function 'cv::line'

Are you trying to run demo.py with a original test_image.png?
This error occurs when the image size is smaller than 1280x720.

**Comment by migero** [comment]
ok found image that was above 1280 and seems to work
